### ISSUE TITLE
Example HTML Files

### ISSUE THREAD

**Issue by askmattcairns** [adambergman/irepemulator#3]
Hi Adam,

I've not been able to get any views to render using this app in the iPad emulator. Could you could provide an example HTML directory to test against?

Thanks!

**Comment by adambergman** [comment]
Try pulling down the latest version and following my instructions at https://github.com/adambergman/irepemulator#how-to-use-this-tool

In iOS9, Apple added a security feature to the UIWebView that made it require URLs to be HTTPS – HTTP URLs would cause the browser to stay on a white screen.  I added the required NSAllowsArbitraryLoads value in the application plist file and that fixed the issue for me.  

If you're still have problems after updating, let me know.
